### ISSUE TITLE
Will you release superpixel average pooling code ?

### ISSUE THREAD

**Issue by idealwei** [bermanmaxim/superpixPool#4]
I see you applied "average pooling" in your paper, but the code your release is "max pooling". In my view, average pooling make more sense in terms of task like semantic segmentation. Will your release "average pooling" ?

**Comment by idealwei** [comment]
I've roughly implemented ["super pixel average pooling"](https://github.com/idealwei/SuperPixelPool-pytorch) myself. Nevertheless, it will be great that you release your  code, that will help a lot.

**Comment by bermanmaxim** [comment]
Hi, not sure, maybe @Mathijssch can give you some advice regarding this.

**Comment by Mathijssch** [comment]
Since we have focused mainly on max-pooling, our [average pooling code](https://github.com/bermanmaxim/superpixPool/blob/master/chainer_supvoxpool/supervoxel_pooling.cu) is only available in chainer (for 3D images), you might be able to get some insights from that. 

We are planning to publish a more complete and well-documented version of the code in the near future, but it's difficult to say when this will be exactly.

**Comment by idealwei** [comment]
Thank you for your reply. I learn a lot in the implementation of "super pixel average pooling" myself. Hope that could help my work.
